spring:
  application:
    name: cloudConsumerInfo

server:
  port: 80


eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.103:2181/eureka/
  instance: 
    instance-id: ${spring.application.name}:${server.port}   #${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true  #访问路径可以显示IP地址     
    
info: 
  app.name: cloudConsumerInfoName
  company.name: zh
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  